# asyncio 的核心概念

Python 中的协程是一种轻量级的并发编程技术，用于处理异步和并发任务。协程允许函数在执行中暂停，等待某些条件满足后再恢复执行，而不会阻塞整个程序。它们通常用于处理 I/O 密集型操作，如网络请求、文件读写、数据库查询等，以提高程序的性能和响应性。

### 一.协程函数的判断

在 Python 中，要判断一个函数是否是协程，您可以使用 `inspect` 模块来检查函数的类型。特别是，您可以使用 `inspect` 模块的 `isasyncgenfunction()` 和 `iscoroutinefunction()` 函数来检查函数是否是异步生成器函数或协程函数。

```python
import asyncio
import inspect


async def async_function():
    await asyncio.sleep(1)


def regular_function():
    pass


async def async_generator():
    yield 1


def regular_generator():
    yield 1


# 判断函数是否是协程函数
print(inspect.iscoroutinefunction(async_function))  # True
print(inspect.iscoroutinefunction(regular_function))  # False

# 判断函数是否是异步生成器函数
print(inspect.isasyncgenfunction(async_generator))  # True
print(inspect.isasyncgenfunction(regular_generator))  # False
```

### 二.事件循环(event_loop)

事件循环（Event Loop）是异步编程中的一个核心概念，它是**用于管理和调度异步任务的机制** 。事件循环负责在程序中协调各种异步操作，使它们能够以非阻塞的方式运行，并在合适的时候执行。

```python
import asyncio


async def my_coroutine():
    print("Start")
    await asyncio.sleep(2)  # 模拟异步操作
    print("End")


# 创建事件循环
loop = asyncio.get_event_loop()

# 运行协程任务
loop.run_until_complete(my_coroutine())

# 关闭事件循环
loop.close()
```

如果我们单独像执行普通函数那样执行一个协程函数，只会返回一个 coroutine 对象

#### 1.获取事件循环对象的方式

**loop=asyncio.get_running_loop():**
获取在当前线程中正在运行的事件循环，如果没有正在运行的事件循环，则会显示错误

**loop=asyncio.get_event_loop():**
获得一个事件循环，如果当前线程还没有事件循环，则创建一个新的事件循环 loop

**loop=asyncio.set_event_loop(loop):**
设置一个事件循环为当前线程的事件循环，配合下面的函数使用

**loop=asyncio.new_event_loop():** 创建一个新的事件循环

#### 2.通过事件循环运行协程函数的方式

**loop.run_until_complete(function_name):**
通过时间循环运行协程函数,这个方法会启动协程的执行并等待它完成。

**asyncio.run(function_name):** 运行协程函数

> 注意:
>
> 1.run 函数是 python3.7 版本新添加的，前面的版本是没有的；
>
> 2.run 函数总是会创建一个新的事件循环并在 run 结束之后关闭事件循环，所以，如果在同一个线程中已经有了一个事件循环，则不能再使用这个函数了，因为同一个线程不能有两个事件循环，而且这个 run 函数不能同时运行两次，因为他已经创建一个了。即同一个线程中是不允许有多个事件循环 loop 的。

**用法区别：**

**loop.run_until_complete():** 这是传统的 asyncio 方法，通常需要创建和管理事件循环(event loop)。您需要首先获取事件循环对象(通常使用 `asyncio.get_event_loop()`)，然后使用 `loop.run_until_complete()` 来运行协程或任务。

**asyncio.run():** 这是 Python 3.7+ 引入的高级方法，它是一个更简化的接口，无需手动创建和管理事件循环。您只需调用 `asyncio.run()` 并传递一个协程或任务，它会自动创建事件循环、运行协程、等待其完成，并在协程完成后关闭事件循环。

**异常处理区别：**

**loop.run_until_complete():** 需要显式处理异常。如果协程或任务引发异常，您需要在 `loop.run_until_complete()` 调用中使用 `try...except` 来捕获并处理异常。

**asyncio.run():** 会自动捕获并处理协程或任务引发的异常，并将异常信息打印到标准错误输出，然后退出程序。

### 三.可暂停等待的对象(awaitable)

"awaitable" 是一个泛指的术语，用于描述可以被 `await` 关键字等待的对象。`awaitable` 允许程序在等待某个操作完成时不会阻塞，并允许其他任务执行。通常指的是以下三种类型的对象之一：

**协程(Coroutine):** 协程是异步编程的基本构建块之一。它是一个可以在异步环境中暂停和恢复执行的函数。协程使用 `async def` 关键字定义，并可以包含 `await` 表达式来暂停执行并等待异步操作的完成。

**异步任务(Async Task):** 任务是协程的一种封装。在 asyncio 中，您可以使用 `asyncio.create_task()` 或 `asyncio.ensure_future()` 来创建任务。任务是协程的扩展，它添加了一些附加功能，例如可以用于取消任务，获取任务状态等。

**Future:** Future 是 asyncio 中表示尚未完成的异步操作的结果的对象。它通常用于表示一个异步操作的结果，可以是成功的结果，也可以是异常。Future 通常由事件循环自动管理和设置。

> 三者关系:
>
> 任务（Task）是协程（Coroutine）的一种封装。通过创建任务，可以将协程放入一个可调度的容器中，并由事件循环管理。
>
> Future 通常与任务和协程一起使用，以表示异步操作的结果。任务（Task）本质上是一个具有与 Future 相关功能的特殊协程，它自动与一个 Future 对象相关联。
>
> 协程（Coroutine）可以包含 `await` 表达式，这些表达式通常返回 Future 对象，表示等待某个异步操作的结果。当协程在 `await` 处暂停时，它会将控制权返回给事件循环，允许事件循环继续执行其他任务。当异步操作完成时，与 `await` 关联的 Future 对象会被标记为已完成，并且协程会继续执行。

总之，协程、任务和 Future 是协同工作的组件，使得异步编程能够以非阻塞的方式高效地进行。任务是协程的扩展，可以由事件循环调度，而 Future 用于表示异步操作的结果，通常与协程一起使用。通过组合使用这些概念，可以实现异步操作的管理和控制。

### 四.任务 Task

#### 1.什么是 Task 任务

`Task`用来**并发调度的** 协程，它代表一个异步任务（也称为协程任务），用于在事件循环中执行协程函数。`Task` 允许您将一个协程函数包装成一个可等待的对象，从而可以在事件循环中并发执行多个协程任务，管理它们的状态和执行顺序。

> 为什么还需要包装呢？
>
> 因为单纯的协程函数仅仅是一个函数而已，将其包装成任务，任务是可以包含各种状态的，异步编程最重要的就是对异步操作状态的把控了。

#### 2.创建任务的方法

**方法一:** task = asyncio.create_task(coro())

**方法二:** task = asyncio.ensure_future(coro())

**方法三:** loop.create_future()

**方法四:** loop.create_task(coro)

```python
import asyncio


async def test_coroutine():
    await asyncio.sleep(1)
    return "Task is complete"


async def main():
    # 创建两个任务
    task1 = asyncio.create_task(test_coroutine())
    task2 = asyncio.ensure_future(test_coroutine())

    # 等待任务完成
    result1 = await task1
    result2 = await task2

    print(result1)
    print(result2)


asyncio.run(main())
```

#### 3.获取某一个任务的方法

**方法一:** task=asyncio.current_task(loop=None)

返回在某一个指定的 loop 中，当前正在运行的任务，如果没有任务正在运行，则返回 None；

如果 loop 为 None，则默认为在当前的事件循环中获取，

**方法二:** asyncio.all_tasks(loop=None)

返回某一个 loop 中还没有结束的任务

### 五.Future

Future 是一个较低层的可等待（awaitable）对象，他表示的是异步操作的最终结果，当一个 Future 对象被等待的时候，协程会一直等待，直到 Future 已经运算完毕。

Future 是 Task 的父类，一般情况下，已不用去管它们两者的详细区别，也没有必要去用 Future，用 Task 就可以了

#### 1.创建 Future 对象

您可以使用 `asyncio.Future()` 构造函数创建一个新的 `Future` 对象。

```python
import asyncio

future = asyncio.Future()
```

#### 2.设置 Future 结果

一旦异步操作完成，您可以使用 `future.set_result(result)` 方法来设置 `Future` 的结果。这将使等待 `Future` 的协程继续执行，并可以获取结果。

```python
import asyncio

future = asyncio.Future()
future.set_result("Completed")


async def my_coroutine():
    result = await future
    print(result)


asyncio.run(my_coroutine())  # 输出 "Completed"
```

#### 3.异常处理

如果异步操作发生异常，您可以使用 `future.set_exception(exception)` 方法来设置 `Future` 的异常。等待 `Future` 的协程将会引发相同的异常。

```python
import asyncio

# 创建一个 Future 对象
future = asyncio.Future()

# 将 Future 对象的结果设置为异常
exception = ValueError("Custom exception")
future.set_exception(exception)

# 在 Future 对象上等待结果
try:
    result = asyncio.run(future)
    print(f"Future result: {result}")
except Exception as e:
    print(f"Error while waiting for Future: {e}")
```

#### 4.检查完成状态

您可以使用 `future.done()` 方法来检查 `Future` 是否已完成，以及 `future.result()` 方法来获取结果（如果 `Future` 已完成）。

```python
import asyncio

future = asyncio.Future()
future.set_result("Completed")

print(future.done())    # 输出 True
print(future.result())  # 输出 "Completed"
```
